### ISSUE TITLE
Artifacts with no name getting created

### ISSUE THREAD

**Issue by kumarkishore1001** [osrmt/osrmt#42]
**Description**
Artifacts with no name getting created.

**Steps to reproduce**
1. Open the application
2. Go to system and new artifact
3. Don't put any name and proceed. Observe that artifact with vacant name has been created.

**Screenshots**
https://screencast.com/t/IrTPd7fS5

**Comment by rquarry** [comment]
I tested adding a new Feature, Requirement, Design, Implementation, and TestCase with no "name" entry. I use "name" because the box should probably be called that, but it's labeled as the artifact name (see screenshot).

Each time I was presented with a message, "Please enter data in all mandatory field [Artifact]". This isn't 100% tested with every entry box combination, but I think this can be closed.

![Capture](https://user-images.githubusercontent.com/54045716/80161070-3b54e300-859d-11ea-9514-f1edf5fd4231.PNG)

**Comment by ZoranPandovski** [comment]
That's awesome. Thanks, @rquarry. I will close this issue for now. If you find new issues feel free to open new bugs.
