### ISSUE TITLE
Displays old logo

### ISSUE THREAD

**Issue by AlanClifford** [osrmt/osrmt#50]
When osrmt starts it displays the old graphic (Earth globe) rather than the new graphic used in the manuals.

**Comment by rquarry** [comment]
I thought this might be an easy fix to submit a pull request for, but I cannot locate the "logo.png" mentioned in the source. The only thing I can think of is that it's located in one of the .jar files, so I'm going to keep looking.

**Comment by ZoranPandovski** [comment]
I think I have copy of it. I will try to find it, if not @AlanClifford has one.

**Comment by rquarry** [comment]
Found it in:
build-resources/common/runtime-lib/resources.jar/resources/images/logo.png

I'll update this if I can get my hands on the image. Worst case, I can probably extract from the help docs, but I doubt it'll be good as the original quality.

**Comment by rquarry** [comment]
Submitted #53

**Comment by rquarry** [comment]
@ZoranPandovski requested I "pull the master and test", but the commit was to the **develop** branch. 

Results:
1. Pulled "master" and built: Still runs with old logo (as expected).
2. Pulled "develop" and built: runs with new logo! (as expected).

Not sure how development branches function on this project, but as long as someone notes that this issue is fixed in **develop** then this can be closed.

**Comment by ZoranPandovski** [comment]
Yes, the develop branch is not merged in master. Thanks
